<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-fileupload.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-timepicker.min.css" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap-fileupload.min.js"></script>
        
        <div class="pageheader">
            <div class="pageicon"><span class="iconfa-laptop"></span></div>
            <div class="pagetitle">
                <h5>PRINCIPAL</h5>
                <h1>Formas de Pagamento</h1>
            </div>
        </div><!--pageheader-->
        <?php 
        	echo $this->alert;
		?>        
        <div class="maincontent">
            <div class="maincontentinner">
            
            
            <div class="widgetbox box-inverse">
                <h4 class="widgettitle">Formas de Pagamento</h4>
                <div class="widgetcontent nopadding">
                	
                	<form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'group1'));?>" method="POST" enctype="multipart/form-data">
                	
							<p>
							<div class="par">
								<label>Imagem</label>
							    <span class="field">
							    <div class="fileupload fileupload-new" data-provides="fileupload">
								<div class="input-append">
								<div class="uneditable-input span3">
								    <i class="iconfa-file fileupload-exists"></i>
								    <span class="fileupload-preview"></span>
								</div>
								<span class="btn btn-file"><span class="fileupload-new">Selecionar arquivo</span>
								<span class="fileupload-exists">Alterar</span>
								<input type="file" name="arquivo1" /></span>
								<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>
								</div>
							    </div>
							    	<img style="width:200px; height:200px;" alt="" src="<?php echo $this->baseUrl(); ?>/upload/grupo/<?php echo $this->grupo1['nomeArquivo']; ?>">
							    </span>
							</div>
							</p>
							                       
                            <p class="stdformbutton">
                                <button class="btn btn-primary" name="up1" value="Salvar" type="submit">Salvar</button>
                            </p>
                    </form>
                </div><!--widgetcontent-->
            </div><!--widget-->
            
            
    </div>
</div>