
  <div class="category-full-image"> 
    <ul class="category-slider">
      <li> <img src="<?php echo $this->baseUrl(); ?>/layout/site/media/page-title-bg.jpg" ></li>
    </ul>
  </div>
  
  <div class="container_9 title-container">
    <div class="page-title first-bg"> Dicas </div>
  </div>
  
  <section  id="columns" class="container_9 clearfix "> 
    <!-- Center -->
    <article id="center_column" class=" grid_12">
    
            <?php echo $this->empresa['descEmpresa']; ?>
          <br />
    </article>
    
  </section>
  