
<img style="width:300px; height:315px;" src="<?php echo $this->baseUrl(); ?>/upload/sliders/<?php echo $this->slider['nomeArquivo']; ?>" alt="" />

	<form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'del'));?>" method="POST" enctype="multipart/form-data">                        
		<p class="stdformbutton">
			<button class="btn btn-primary" name="up" value="Excluir" type="submit">Excluir</button>
			
			<button class="btn " name="up" value="Cancelar" type="submit">Cancelar</button>
		</p>
	</form>