
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Login - Aguia telas</title>
<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/layout/favicon.ico" type="image/x-icon"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/style.default.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/style.shinyblue.css" type="text/css" />

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-migrate-1.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-ui-1.10.3.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/modernizr.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/custom.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#login').submit(function(){
            var u = jQuery('#username').val();
            var p = jQuery('#password').val();
            if(u == '' && p == '') {
                jQuery('.login-alert').fadeIn();
                return false;
            }
        });
    });
</script>
</head>

<body class="loginpage">

<div class="loginpanel">
    <div class="loginpanelinner">
        <div class="logo animate0 bounceIn">
            <img style="width:250px;" src="<?php echo $this->baseUrl(); ?>/layout/site/img/logomarca.png" alt="" />
        </div>
        
        <form id="login" action="<?php echo $this->url(array('action'=>'index'));?>" method="post">
        
            <div class="inputwrapper login-alert">
                <div class="alert alert-error">Usuário ou senha inválido</div>
            </div>
            
            <div class="inputwrapper login-alert">
                <?php echo $this->alert; ?>
            </div>
            
            
            <div class="inputwrapper animate1 bounceIn">
                <input type="text" name="usuarioLogin" id="username" placeholder="Usuário" />
            </div>
            <div class="inputwrapper animate2 bounceIn">
                <input type="password" name="senhaLogin" id="password" placeholder="Senha" />
            </div>
            <div class="inputwrapper animate3 bounceIn">
                <button name="submit">Entrar</button>
            </div>
        </form>
    </div><!--loginpanelinner-->
</div><!--loginpanel-->

<div class="loginfooter">
	<p>
    	<a href="http://www.criattus.com.br" target="_blank" title="Desenvolvido por">
    		<img style="width:130px;" alt="Criattus" src="<?php echo $this->baseUrl(); ?>/layout/adm/images/logo-criattus-white.png">
		</a>
    </p>
</div>

</body>
</html>
