<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-fileupload.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-timepicker.min.css" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap-fileupload.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.maskedinput-1.3.js" type="text/javascript"></script>


		<div class="pageheader">
            <div class="pageicon"><span class="iconfa-tags"></span></div>
            <div class="pagetitle">
                <h5>PRODUTOS</h5>
                <h1>Categorias</h1>
            </div>
        </div><!--pageheader-->
        
        <div class="maincontent">
            <div class="maincontentinner">            
            <div class="widgetbox box-inverse">
                <h4 class="widgettitle">Adicionar Categoria</h4>
                <div class="widgetcontent nopadding">
                	<form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'add'));?>" method="POST" enctype="multipart/form-data">
                	
                			<p>
                			<div class="par">
								<label>Imagem de capa</label>
							    <span class="field">
							    <div class="fileupload fileupload-new" data-provides="fileupload">
								<div class="input-append">
								<div class="uneditable-input span3">
								    <i class="iconfa-file fileupload-exists"></i>
								    <span class="fileupload-preview"></span>
								</div>
								<span class="btn btn-file"><span class="fileupload-new">Selecionar arquivo</span>
								<span class="fileupload-exists">Alterar</span>
								<input type="file" name="arquivo" /></span>
								<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>
								</div>
							    </div>
							    </span>
							</div>
                			</p>
                	
                            <p>
                                <label>Descrição da categoria</label>
                                <span class="field">
                                	<input type="text" name="descCategoria" id="" class="input-xxlarge" />
                                </span>
                            </p>
                                    
                            <p class="stdformbutton">
                                <button class="btn btn-primary" name="up" value="Adicionar" type="submit">Adicionar</button>
                            </p>
                    </form>
                </div><!--widgetcontent-->
            </div><!--widget-->
            
