
<h2>Tem certeza que deseja excluir esta categoria?</h2>

<br />
<h4>IMPORTANTE:</h4>
<h4>Ao excluir uma categoria, está excluindo automaticamente todos os serviços vinculados.</h4>
<br />

<?php 
	echo '<h3>'.$this->categoria['categoriaServico'].'</h3>';
?>

	<form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'del'));?>" method="POST" enctype="multipart/form-data">                        
		<p class="stdformbutton">
			<button class="btn btn-primary" name="up" value="Excluir" type="submit">Excluir</button>
			<button class="btn " name="up" value="Cancelar" type="submit">Cancelar</button>
		</p>
	</form>

