
<h2>Tem certeza que deseja excluir esse Produto?</h2>

<img style="width:300px; height:215px;" src="<?php echo $this->baseUrl(); ?>/upload/produtos/<?php echo $this->produto['nomeArquivo']; ?>" alt="" />
<h4><?php echo $this->produto['tituloProduto']; ?></h4>

<br /><br /><br />

	<form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'del'));?>" method="POST" enctype="multipart/form-data">                        
		<p class="stdformbutton">
			<button class="btn btn-primary" name="up" value="Excluir" type="submit">Excluir</button>
			<button class="btn " name="up" value="Cancelar" type="submit">Cancelar</button>
		</p>
	</form>

