<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/isotope.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-migrate-1.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery-ui-1.10.3.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/modernizr.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/jquery.slimscroll.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-fileupload.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-timepicker.min.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap-fileupload.min.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function(){
        
        //Replaces data-rel attribute to rel.
        //We use data-rel because of w3c validation issue
        jQuery('a[data-rel]').each(function() {
            jQuery(this).attr('rel', jQuery(this).data('rel'));
        });
        
        jQuery("#medialist a").colorbox();
        
    });
    jQuery(window).load(function(){
        jQuery('#medialist').isotope({
            itemSelector : 'li',
            layoutMode : 'fitRows'
        });
        
        // Media Filter
        jQuery('#mediafilter a').click(function(){
	    
            var filter = (jQuery(this).attr('href') != 'all')? '.'+jQuery(this).attr('href') : '*';
            jQuery('#medialist').isotope({ filter: filter });
	    
            jQuery('#mediafilter li').removeClass('current');
            jQuery(this).parent().addClass('current');
	    
            return false;
        });
    });
</script>
        <div class="pageheader">
            <div class="pageicon"><span class="iconfa-tags"></span></div>
            <div class="pagetitle">
                <h5>PRODUTOS</h5>
                <h1>Categorias</h1>
            </div>
        </div><!--pageheader-->
        <?php 
        echo $this->alert;
        ?>
        <div class="maincontent">
            <div class="maincontentinner">
            
                
                <a href="<?php echo $this->baseUrl(); ?>/admin/categorias/add" class="btn btn-inverse alertinverse" >
                	Adicionar Categoria
                </a>
                
                <br /><br />
                
                <div class="peoplelist">
                
                <?php 
                $k = 1;
                foreach ($this->categorias as $categoria): 
                
	                if ($k == 1){
	                	echo "<div class='row-fluid'>";
	                	$endDiv = null;
	                	$k = 2;
	                }elseif ($k == 2){
	                	$endDiv = '</div>';
	                	$k = 1;
	                }else{
	                	$k++;
	                	$endDiv = null;
	                }
				?>
                        <div class="span6">                        
                            <div class="peoplewrapper">
                            
                    
                        	<span id="medialist" >
                            	<a href="<?php echo $this->baseUrl(); ?>/admin/categorias/del/id/<?php echo $categoria['idCategoria']; ?>" >
                            		<button class="btn trash"><span class="icon-trash"> </span></button>
                            	</a>
                            </span>
                            
                                <div class="peopleinfo">
                                
                                <form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'index'));?>" method="POST" enctype="multipart/form-data">
                                
                                <input type="hidden" name="idCategoria" value="<?php echo $categoria['idCategoria']; ?>"/>
                                
                                    <ul>
                                    	<li>
                                    		<img style="width:280px; height:200px;" alt="" src="<?php echo $this->baseUrl(); ?>/upload/categorias/<?php echo $categoria['nomeArquivo']; ?>">
											<label>Imagem</label>
										    <div class="fileupload fileupload-new" data-provides="fileupload">
											<div class="input-append">
											<div class="uneditable-input span2">
											    <i class="iconfa-file fileupload-exists"></i>
											    <span class="fileupload-preview"></span>
											</div>
											<span class="btn btn-file"><span class="fileupload-new">Selecionar arquivo</span>
											<span class="fileupload-exists">Alterar</span>
											<input type="file" name="arquivo" /></span>
											<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>
											</div>
										    </div>
                                    	</li>
                                    
                                    	<li><label>Categoria:</label>
                                    		<input type="text" name="descCategoria" id="" class="input-xlarge" value="<?php echo $categoria['descCategoria']; ?>" />
                                    	</li>
                                        
                                        <li><br />
                                        	<button type="submit" class="btn btn-primary" name="up" value="Salvar" >Salvar</button>
                                        </li>
                                        
                                    </ul>
                                    </form>
                                </div><!-- peopleinfo -->
                            </div><!-- peoplewrapper -->
                        </div><!-- span6 -->
                    
                <?php                	
                	echo $endDiv.'<!--END DIV -->';
                endforeach; 
                ?>
                
                </div><!--peoplelist-->
                
            </div><!--maincontentinner-->
        </div><!--maincontent-->
        
        