<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-fileupload.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/layout/adm/css/bootstrap-timepicker.min.css" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/bootstrap-fileupload.min.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/layout/adm/js/tinymce2/js/tinymce/tinymce.min.js"></script>


<script>
tinymce.init({
    selector: "textarea#elm1",
    theme: "modern",

    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
         "save table contextmenu directionality emoticons template paste textcolor"
   ],
   content_css: "css/content.css",
   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image |  preview  fullpage | forecolor backcolor ", 
   menu: {  
   }

 }); 
</script>

        
        <div class="pageheader">
            <div class="pageicon"><span class="iconfa-briefcase"></span></div>
            <div class="pagetitle">
                <h5>FOTOS</h5>
                <h1>Fotos</h1>
            </div>
        </div><!--pageheader-->
        <?php 
        	echo $this->alert;
		?>        
        <div class="maincontent">
            <div class="maincontentinner">

            <form name="uploadfile" class="stdform stdform2" action="<?php echo $this->url(array('action'=>'edit'));?>" method="POST" enctype="multipart/form-data">
            
            <div class="widgetbox box-inverse">
                <h4 class="widgettitle">Editar Foto</h4>
                <div class="widgetcontent nopadding">
                	
					<p>
					<div class="par">
						<label>Imagem</label>
					    <span class="field">
					    <img style="width:250px; height:100px;" alt="" src="<?php echo $this->baseUrl(); ?>/upload/fotos/<?php echo $this->fotos['nomeArquivo']; ?>">
					    <div class="fileupload fileupload-new" data-provides="fileupload">
						<div class="input-append">
						<div class="uneditable-input span3">
						    <i class="iconfa-file fileupload-exists"></i>
						    <span class="fileupload-preview"></span>
						</div>
						<span class="btn btn-file"><span class="fileupload-new">Selecionar arquivo</span>
						<span class="fileupload-exists">Alterar</span>
						<input type="file" name="arquivo1" /></span>
						<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remover</a>
						</div>
					    </div>
					    </span>
					</div>
					</p>
					
					<p>
						<label>Foto</label>
						<span class="field">
							<input type="text" name="tituloFoto" id="firstname2" class="input-xxlarge" value="<?php echo $this->fotos['tituloFotos']; ?>"/>
						</span>
					</p>
					
					<p>
                	<textarea rows="15" id="elm1" name="descricaoFoto"><?php echo $this->fotos['descricaoFotos']; ?></textarea>
            		</p>
                	
                	<input type="hidden" name="foto_idEventos" value="<?php echo $this->fotos['fotos_idEventos']; ?>"/>
                    <input type="hidden" name="idFotos" value="<?php echo $this->fotos['idFotos']; ?>"/>
                	
                	<p class="stdformbutton">
                		<button class="btn btn-primary" name="up" value="Confirmar" type="submit">Confirmar</button>
                	</p>

                </div><!--widgetcontent-->
            </div><!--widget-->
                    
			</form>
                    