
  <div class="category-full-image"> 
    

    <ul class="category-slider">
      <li> <img src="<?php echo $this->baseUrl(); ?>/layout/site/media/page-title-bg.jpg" ></li>
    </ul>
  </div>
  <div class="container_9 title-container">
    <div class="page-title first-bg"> <?php echo $this->evento['descricao']; ?> </div>
  </div>
  <section  id="columns" class="container_9 clearfix col2-right"> 
    
    <!-- Center -->
    <article id="center_column" class=" grid_5">
      
      <ul class="products-grid">
      
      <?php
       $k = 1; 
       foreach ($this->fotos as $fotos):
 
          if ($k == 3) {
          	$row = 'last';
          	$k = 0;
          }else{
          	$row = 'first';
          }
       ?>
        <li class="item <?php echo $row; ?> fadeIn animated"> 
            <a rel="prettyPhoto[pp_gal]" class="fa-search-btn first-bg"  href="<?php echo $this->baseUrl(); ?>/upload/fotos/<?php echo $fotos['nomeArquivo']; ?>"> 
                Visualizar <i class="icon-search"></i>
            </a>  
            
            <img style="width: 268px; height: 180px;" src="<?php echo $this->baseUrl(); ?>/upload/fotos/<?php echo $fotos['nomeArquivo']; ?>" >
            <h2 class="product-name">  
                <b>
                <?php echo $fotos['tituloFoto']; ?>
                </b> 
            </h2>
        </li>
        <?php
        $k++;  
        endforeach; ?>

      </ul>

    </article>

<!-- RIGHT -->
<aside id="right_column" class="column grid_2 omega"> 
      
      <!-- Block categories module -->
      <div id="categories_block_left" class="block block-news">
        <h4 class="title_block">Eventos</h4>
        <div class="block_content">
          <ul class="tree dhtml">
            
            <?php foreach ($this->eventos as $evento): ?>
            <li> 
                <a href="<?php echo $this->baseUrl(); ?>/fotos/view/id/<?php echo $evento['id']; ?>"  title="">
                    <?php echo $evento['descricao']; ?>
                </a>
            </li>
            <?php endforeach;  ?>

            
            
          </ul>
        </div>
      </div>
      <!-- /Block categories module --> 
      
    </aside>
    
    
  </section>

